version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    tty: true
    depends_on:
      - db
    working_dir: /var/www
    volumes:
      - ./:/var/www

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www
    links:
      - app

  db:
    image: postgres:12
    container_name: db
    restart: always
    volumes:
      - db__data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1-17-0619
      POSTGRES_USER: 1-17-0619
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"

volumes:
  db__data:
